# -*- coding: utf-8 -*-
"""taller 13 p1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m9zDFk3j4dbkbMW_HJG8je75gbWyunn8
"""

#se solicitan los valores para la longitud de los vectores
n = int(input("Ingrese la longitud de los vectores: "))


vector1 = [0] * n
vector2 = [0] * n


print("Ingrese los elementos del primer vector:")
for i in range(n):
    vector1[i] = int(input())

print("Ingrese los elementos del segundo vector:")
for i in range(n):
    vector2[i] = int(input())


producto_escalar = 0
for i in range(n):
    producto_escalar += vector1[i] * vector2[i]


print("El producto escalar de los vectores es:", producto_escalar)

import numpy as np

2

filas_a = int(input("Introduzca el número de filas de la matriz A: "))
columnas_a = int(input("Introduzca el número de columnas de la matriz A: "))
filas_b = int(input("Introduzca el número de filas de la matriz B: "))
columnas_b = int(input("Introduzca el número de columnas de la matriz B: "))


A = np.zeros((filas_a, columnas_a))
B = np.zeros((filas_b, columnas_b))

print("Introduzca los valores de la matriz A: ")
for i in range(filas_a):
    for j in range(columnas_a):
        A[i,j] = float(input(f"A4[{i},{j}]: "))

print("Introduzca los valores de la matriz B: ")
for i in range(filas_b):
    for j in range(columnas_b):
        B[i,j] = float(input(f"B[{i},{j}]: "))


tres_A = 3 * A
cuatro_B = 4 * B
suma_A_B = A + B
producto_B_A = np.dot(B, A)


print("3A =")
print(tres_A)
print("4B =")
print(cuatro_B)
print("A + B =")
print(suma_A_B)
print("B × A =")
print(producto_B_A)